#server
server:
  port: 10010


#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    #  jpa
    hibernate:
      ddl-auto: update
#
#    #jpa format
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    check-template-location: true

  #log
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  #Redis
  session:
    store-type: redis

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            client-id: AObksQAglEMKUmS5Sw34
            client-secret: QaLQttXiBq
            redirect-uri: http://localhost:10010/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, mobile

          kakao:
            client-name: kakao
            client-id: a44356540755069377eb33da82819781
            client-secret: t0w5D5LmWAsW9UfqQ3VGE5f7wQqS49MM
            redirect-uri: http://localhost:10010/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname, profile_image

          google:
            client-id: 495216812187-dt5li9h855lhj4ph12v965nsc93a747h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:10010/login/oauth2/code/google
            scope: email, profile

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

file:
 uploadDir: C:/LunchBoxDonation/

